### ISSUE TITLE
reddit popup 

### ISSUE THREAD

**Issue by viktorblack** [Dysrhythmic/ffxiv-raf-bot#1]
anyway to get past the popup i cant post on reddit?
![dddd](https://user-images.githubusercontent.com/70507189/131041506-79f95975-9c1e-4407-8b5d-81f382fa9433.png)

**Comment by Dysrhythmic** [comment]
I'm unable to replicate this- it seems to be blocked from popping up for me. You could try clicking "Always Block" and see if that keeps it from appearing in the future. If that doesn't work, you could try some of the solutions suggested [here](https://stackoverflow.com/questions/38684175/how-to-click-allow-on-show-notifications-popup-using-selenium-webdriver) such as having the driver "press" the escape key once it reaches that page to dismiss it.

I'll try to replicate the issue some more tomorrow so that I can explore some potential fixes. If you find a fix before me, feel free to send a pull request!

**Comment by viktorblack** [comment]
sadly i tried some stuff but i dont know anything about coding so i prob did it wrong but yeah i can't seem to fix it

**Comment by Dysrhythmic** [comment]
I added a second branch to this repo to test fixes for this issue. I added a function that waits a bit and then sends the escape key to the browser to try and dismiss the popup. I was still unable to get the popup to show for me so I am unsure how well that will work. Let me know!

The second branch can be found [here](https://github.com/Dysrhythmic/ffxiv-raf-bot/tree/dismiss-popup)

**Comment by viktorblack** [comment]
just tried it out seems to be working for now

**Comment by Dysrhythmic** [comment]
Awesome, glad to hear it!

Is the popup no longer showing up for you or is it showing and then being dismissed? If it is being dismissed after appearing then it seems like the escape key is working properly and I can merge the branch with this fix to the main branch and mark this issue as resolved.

**Comment by viktorblack** [comment]
so its seems that its being dismissed =)

**Comment by Dysrhythmic** [comment]
Sweet! Glad this is resolved. Let me know if you have any other issues.
